const tanggal = document.getElementById("tanggal");
const bulan = document.getElementById("bulan");
const tahun = document.getElementById("tahun");

for(let i=1;i<=31;i++){
    tanggal.innerHTML += `<option value="${i}">${i}</option>`;
}

const namaBulan = ["Januari","Februari","Maret","April","Mei","Juni",
"Juli","Agustus","September","Oktober","November","Desember"];

for(let i=0;i<12;i++){
    bulan.innerHTML += `<option value="${i+1}">${namaBulan[i]}</option>`;
}

for(let i=1980;i<=2024;i++){
    tahun.innerHTML += `<option value="${i}">${i}</option>`;
}

function jumlahDigit(angka){
    return angka.toString().split('').reduce((a,b)=>a+parseInt(b),0);
}

const deskripsiGarisHidup = [
    '',
    `Garis Hidup 1: Anda adalah pemimpin alami, penuh semangat, dan memiliki kepercayaan diri yang tinggi. Mandiri dan berani mengambil keputusan, Anda tidak takut menghadapi tantangan baru. Orang dengan garis hidup 1 biasanya memiliki visi yang jelas dan mampu menginspirasi orang lain untuk mengikuti jejaknya. Anda suka menjadi yang terdepan, tidak mudah menyerah, dan selalu berusaha mencapai tujuan dengan cara-cara inovatif. Namun, kadang Anda bisa terlalu keras kepala atau terlalu fokus pada diri sendiri. Belajarlah untuk mendengarkan pendapat orang lain dan bekerja sama dalam tim. Sisi positif Anda adalah keberanian, tekad, dan kemampuan memimpin. Sisi negatifnya, Anda perlu mengendalikan ego dan belajar lebih sabar. Jika mampu menyeimbangkan sifat-sifat ini, Anda akan menjadi sosok yang sangat berpengaruh dan dihormati di lingkungan Anda.<br><br>Anda juga memiliki energi besar untuk memulai sesuatu yang baru, dan seringkali menjadi pelopor dalam berbagai bidang. Jangan ragu untuk terus mengembangkan potensi kepemimpinan Anda, namun tetap jaga hubungan baik dengan orang-orang di sekitar Anda.`,
    `Garis Hidup 2: Anda adalah sosok pendamai, sensitif, dan sangat peka terhadap perasaan orang lain. Kerja sama dan harmoni adalah kunci hidup Anda. Anda mudah berempati, suka membantu, dan sering menjadi penengah dalam konflik. Orang dengan garis hidup 2 sangat cocok bekerja dalam tim, karena mampu menciptakan suasana yang nyaman dan saling mendukung. Anda juga dikenal sebagai sahabat yang setia dan pasangan yang pengertian. Namun, kadang Anda terlalu mengalah atau sulit mengambil keputusan sendiri. Belajarlah untuk lebih percaya diri dan tidak takut menyuarakan pendapat. Sisi positif Anda adalah kelembutan, diplomasi, dan kemampuan membangun hubungan baik. Sisi negatifnya, Anda perlu menghindari sikap terlalu sensitif atau mudah tersinggung. Dengan menyeimbangkan sifat-sifat ini, Anda akan menjadi sosok yang sangat dicintai dan dihargai oleh banyak orang.<br><br>Anda juga memiliki bakat dalam seni, musik, atau bidang yang membutuhkan kepekaan rasa. Jangan ragu untuk mengekspresikan perasaan Anda secara kreatif dan terus kembangkan kemampuan bekerja sama dengan orang lain.`,
    `Garis Hidup 3: Bagi mereka yang jumlah angka hari lahirnya 3, ekspresi, sosialisasi, dan kreativitas adalah pelajaran utama dalam hidup. Anda adalah entertainer kelas dunia, penuh optimisme, dan sangat berbakat dalam bidang kreatif—baik verbal, tulisan, akting, maupun seni lainnya. Misi hidup Anda adalah mencapai kesuksesan melalui ekspresi diri. Sisi cerah dari kepribadian ini adalah harmoni, keindahan, kesenangan, dan keinginan membagikan kreativitas kepada dunia. Mengasah kemampuan ekspresi kreatif adalah tujuan tertinggi Anda.<br><br>Karakter Anda hangat, bersahabat, pembicara yang baik, sosial, dan terbuka. Anda bukan hanya menyenangkan untuk didengar, tetapi juga pendengar yang baik. Anda selalu diterima dalam situasi sosial dan mampu membuat orang lain merasa nyaman. Potensi imajinasi kreatif Anda sangat besar, meski kadang tidak selalu diasah. Sikap Anda terhadap hidup hampir selalu positif, riang, dan terbuka. Anda mampu menghadapi tantangan dengan efektif dan cepat kembali bersemangat. Anda juga memiliki tata krama yang baik dan peka terhadap perasaan orang lain. Hidup dijalani sepenuhnya, sering tanpa kekhawatiran akan hari esok.<br><br>Namun, Anda kurang pandai mengelola keuangan karena tidak menganggapnya penting. Uang akan dibelanjakan saat ada, dan ditahan saat tidak ada. Sisi negatifnya, sikap Anda bisa terlalu ringan hingga terkesan superfisial, kemampuan Anda bisa tersebar dan kehilangan fokus. Anda adalah teka-teki, sering berganti mood, dan cenderung menghindar. Sulit untuk menetap di satu tempat. Jaga agar tidak selalu mengkritik, tidak sabaran, atau terlalu optimistik.<br><br>Garis hidup 3 memberikan kemampuan di atas rata-rata dalam seni: melukis, desain, menulis, musik, teater, atau bahkan semuanya. Anda selalu gembira, penuh inspirasi, dan mencari stimulasi dari orang-orang yang sejalan. Sifat Anda yang ramai mendukung kesuksesan, terutama jika Anda mampu memfokuskan energi dan talenta pada minat yang tepat.`,
    `Garis Hidup 4: Anda adalah pribadi yang disiplin, pekerja keras, dan sangat terorganisir. Keteraturan dan stabilitas adalah fondasi hidup Anda. Anda dapat diandalkan dalam segala situasi, selalu menyelesaikan tugas dengan teliti dan penuh tanggung jawab. Orang dengan garis hidup 4 biasanya sangat sabar, tekun, dan tidak mudah menyerah meski menghadapi rintangan. Anda suka merencanakan segala sesuatu dengan detail dan tidak suka perubahan mendadak. Namun, kadang Anda bisa terlalu kaku atau sulit menerima ide baru. Belajarlah untuk lebih fleksibel dan terbuka terhadap perubahan. Sisi positif Anda adalah ketekunan, kejujuran, dan loyalitas. Sisi negatifnya, Anda perlu menghindari sikap keras kepala atau terlalu perfeksionis. Jika mampu menyeimbangkan sifat-sifat ini, Anda akan menjadi fondasi yang kuat bagi keluarga, teman, dan lingkungan kerja Anda.<br><br>Anda juga memiliki bakat dalam bidang teknik, administrasi, atau pekerjaan yang membutuhkan ketelitian tinggi. Jangan ragu untuk terus mengembangkan kemampuan manajemen dan organisasi Anda.`,
    `Garis Hidup 5: Anda adalah petualang sejati, penuh semangat, dan sangat fleksibel. Kebebasan adalah hal terpenting dalam hidup Anda. Anda suka mencoba hal-hal baru, mudah beradaptasi, dan tidak suka rutinitas yang monoton. Orang dengan garis hidup 5 biasanya sangat komunikatif, suka bertemu orang baru, dan selalu mencari pengalaman seru. Anda juga pandai memotivasi orang lain untuk keluar dari zona nyaman. Namun, kadang Anda bisa terlalu impulsif atau sulit berkomitmen pada satu hal. Belajarlah untuk lebih fokus dan bertanggung jawab atas pilihan Anda. Sisi positif Anda adalah keberanian, kreativitas, dan kemampuan beradaptasi. Sisi negatifnya, Anda perlu menghindari sikap tidak sabaran atau terlalu suka mengambil risiko. Dengan menyeimbangkan sifat-sifat ini, Anda akan menjalani hidup yang penuh warna dan inspirasi bagi banyak orang.<br><br>Anda juga memiliki bakat dalam bidang komunikasi, pemasaran, atau pekerjaan yang dinamis. Jangan ragu untuk terus mengeksplorasi dunia dan berbagi pengalaman dengan orang lain.`,
    `Garis Hidup 6: Anda adalah sosok penyayang, penuh tanggung jawab, dan sangat peduli pada keluarga serta orang-orang di sekitar. Anda suka membantu, sering menjadi tempat curhat, dan selalu berusaha menciptakan suasana harmonis. Orang dengan garis hidup 6 biasanya sangat setia, rela berkorban, dan memiliki naluri keibuan atau kebapakan yang kuat. Anda juga pandai merawat, mengayomi, dan menjaga keharmonisan dalam hubungan. Namun, kadang Anda bisa terlalu mengatur atau sulit melepaskan orang yang disayangi. Belajarlah untuk memberi ruang dan kepercayaan pada orang lain. Sisi positif Anda adalah kasih sayang, tanggung jawab, dan kepedulian. Sisi negatifnya, Anda perlu menghindari sikap posesif atau terlalu mencampuri urusan orang lain. Jika mampu menyeimbangkan sifat-sifat ini, Anda akan menjadi sumber kebahagiaan dan ketenangan bagi banyak orang.<br><br>Anda juga memiliki bakat dalam bidang pendidikan, kesehatan, atau pekerjaan sosial. Jangan ragu untuk terus menebar kebaikan dan menjadi teladan bagi lingkungan Anda.`,
    `Garis Hidup 7: Anda adalah pemikir mendalam, analitis, dan sangat intuitif. Anda suka belajar hal baru, merenung, dan mencari makna di balik setiap peristiwa. Orang dengan garis hidup 7 biasanya cenderung introvert, suka ketenangan, dan lebih nyaman bekerja sendiri. Anda juga memiliki rasa ingin tahu yang besar dan kemampuan untuk memahami hal-hal yang tidak terlihat oleh orang lain. Namun, kadang Anda bisa terlalu tertutup atau sulit mempercayai orang lain. Belajarlah untuk lebih terbuka dan berbagi pemikiran dengan orang di sekitar. Sisi positif Anda adalah kebijaksanaan, ketelitian, dan intuisi tajam. Sisi negatifnya, Anda perlu menghindari sikap terlalu kritis atau mudah merasa kesepian. Dengan menyeimbangkan sifat-sifat ini, Anda akan menjadi sumber inspirasi dan pengetahuan bagi banyak orang.<br><br>Anda juga memiliki bakat dalam bidang penelitian, filsafat, atau pekerjaan yang membutuhkan analisis mendalam. Jangan ragu untuk terus mengembangkan wawasan dan membagikan pengetahuan Anda.`,
    `Garis Hidup 8: Anda adalah pribadi yang ambisius, tegas, dan memiliki jiwa kepemimpinan yang kuat. Suka tantangan, Anda tidak takut mengambil risiko demi meraih kesuksesan. Orang dengan garis hidup 8 biasanya pandai mengatur keuangan, organisasi, dan memiliki insting bisnis yang tajam. Anda juga mampu memotivasi orang lain untuk bekerja keras dan mencapai tujuan bersama. Namun, kadang Anda bisa terlalu keras atau terlalu fokus pada materi. Belajarlah untuk menyeimbangkan ambisi dengan empati dan kepedulian pada orang lain. Sisi positif Anda adalah ketegasan, keberanian, dan kemampuan manajerial. Sisi negatifnya, Anda perlu menghindari sikap otoriter atau terlalu materialistis. Jika mampu menyeimbangkan sifat-sifat ini, Anda akan menjadi sosok sukses dan dihormati.<br><br>Anda juga memiliki bakat dalam bidang bisnis, manajemen, atau pekerjaan yang membutuhkan kepemimpinan. Jangan ragu untuk terus mengembangkan potensi dan berbagi keberhasilan dengan orang lain.`,
    `Garis Hidup 9: Anda adalah sosok dermawan, idealis, dan sangat peduli pada kemanusiaan. Jiwa sosial Anda tinggi, suka menolong, dan selalu berusaha membuat dunia menjadi tempat yang lebih baik. Orang dengan garis hidup 9 biasanya memiliki visi besar, penuh kasih, dan rela berkorban demi kepentingan bersama. Anda juga pandai memotivasi orang lain untuk berbuat baik dan tidak segan membantu siapa saja yang membutuhkan. Namun, kadang Anda bisa terlalu idealis atau sulit menerima kenyataan. Belajarlah untuk lebih realistis dan menjaga keseimbangan antara memberi dan menerima. Sisi positif Anda adalah empati, kemurahan hati, dan semangat kemanusiaan. Sisi negatifnya, Anda perlu menghindari sikap terlalu mengorbankan diri atau mudah kecewa. Dengan menyeimbangkan sifat-sifat ini, Anda akan menjadi inspirasi bagi banyak orang.<br><br>Anda juga memiliki bakat dalam bidang sosial, kemanusiaan, atau pekerjaan yang berhubungan dengan pelayanan masyarakat. Jangan ragu untuk terus menebar kebaikan dan memperjuangkan nilai-nilai kemanusiaan.`,
    `Garis Hidup 0: Anda adalah pribadi yang unik, penuh potensi, dan mudah beradaptasi dalam berbagai situasi. Anda sering menjadi inspirasi bagi orang lain karena cara pandang dan pendekatan hidup yang berbeda. Orang dengan garis hidup 0 biasanya memiliki kemampuan untuk melihat peluang di tengah tantangan dan mampu bangkit dari berbagai kesulitan. Anda juga kreatif, inovatif, dan tidak takut mencoba hal-hal baru. Namun, kadang Anda bisa merasa kurang percaya diri atau bingung menentukan arah hidup. Belajarlah untuk lebih fokus dan percaya pada kemampuan diri sendiri. Sisi positif Anda adalah fleksibilitas, kreativitas, dan daya tahan. Sisi negatifnya, Anda perlu menghindari sikap mudah menyerah atau terlalu sering berubah-ubah. Jika mampu menyeimbangkan sifat-sifat ini, Anda akan mampu meraih banyak pencapaian luar biasa.<br><br>Anda juga memiliki bakat dalam bidang seni, teknologi, atau pekerjaan yang membutuhkan inovasi. Jangan ragu untuk terus mengeksplorasi potensi dan menjadi inspirasi bagi lingkungan Anda.`
];

function hitung(){
    let tgl = tanggal.value;
    let bln = bulan.value;
    let thn = tahun.value;

    let gabung = tgl + bln + thn;
    let hasil1 = jumlahDigit(gabung);
    let hasil2 = hasil1 > 9 ? jumlahDigit(hasil1) : hasil1;

    document.getElementById("outTgl").value = tgl;
    document.getElementById("outBln").value = bln;
    document.getElementById("outThn").value = thn;
    document.getElementById("hasil1").value = hasil1;
    document.getElementById("hasil2").value = hasil2;
    document.getElementById("hasilAkhir").value = hasil2;

    document.getElementById("judulHasil").innerHTML =
        "Tanggal Lahir Anda Berada Pada Garis Hidup " + hasil2;

    let deskripsi = deskripsiGarisHidup[hasil2] || 'Deskripsi kepribadian belum tersedia.';
    document.getElementById("deskripsi").innerHTML = deskripsi;
}

function resetForm(){
    location.reload();
}